### ISSUE TITLE
Remaining submission process screens & API mockups

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#326]
- [x] Agreement & permissions slider #131 
- [x] Login with Email or Twitter (related: #133) 
- [x] Email submission response
- [x] Edit profile info (related: #132 )
- [x] My submissions screen [ entries display status & permission settings ] #214
- [x] Monthly Assignment panel (#231)

Also related: #216

**Comment by dmitrizzle** [comment]
Login with email doesn't make it obvious where to type the email address (the placeholder isn't obviously editable)
